name: libstreet
description: Rendering coU streets
version: 0.0.0
dependencies:
  stagexl: "^0.12.0+1"
  transmit:
        git:
          ref: master
          url: git://github.com/ChildrenOfUr/transmit.git
